// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy81XrL6AePl5Bbrhrycs3it_ldxbcOfc',
    appId: '1:534344268507:web:65406e0a831e74a14b2afe',
    messagingSenderId: '534344268507',
    projectId: 'masraf-yonetim',
    authDomain: 'masraf-yonetim.firebaseapp.com',
    storageBucket: 'masraf-yonetim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriZH1gQegKHTRhoIfF8I2F8nczFEuRSo',
    appId: '1:534344268507:android:2958fe1870cd4d714b2afe',
    messagingSenderId: '534344268507',
    projectId: 'masraf-yonetim',
    storageBucket: 'masraf-yonetim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGjGVDfbcDux6OQ-F7zaLkrnwGAoC8No',
    appId: '1:534344268507:ios:d3565c04b07cde594b2afe',
    messagingSenderId: '534344268507',
    projectId: 'masraf-yonetim',
    storageBucket: 'masraf-yonetim.firebasestorage.app',
    iosBundleId: 'com.example.masrafYonetim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGjGVDfbcDux6OQ-F7zaLkrnwGAoC8No',
    appId: '1:534344268507:ios:d3565c04b07cde594b2afe',
    messagingSenderId: '534344268507',
    projectId: 'masraf-yonetim',
    storageBucket: 'masraf-yonetim.firebasestorage.app',
    iosBundleId: 'com.example.masrafYonetim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy81XrL6AePl5Bbrhrycs3it_ldxbcOfc',
    appId: '1:534344268507:web:0d815a88c9ba86074b2afe',
    messagingSenderId: '534344268507',
    projectId: 'masraf-yonetim',
    authDomain: 'masraf-yonetim.firebaseapp.com',
    storageBucket: 'masraf-yonetim.firebasestorage.app',
  );
}
